### ISSUE TITLE
Libressl Dockerfile missing

### ISSUE THREAD

**Issue by milkpirate** [Adam-Ant/docker-busybox-base#2]
https://github.com/spritsail/busybox/blob/libressl/Dockerfile -> 404 (from https://hub.docker.com/r/spritsail/busybox)

**Comment by frebib** [comment]
This was moved to it's own repo, but has since been replaced with OpenSSL. We don't use the libressl/openssl images any more. Was there something particular you wanted these for? I don't recommend using them. https://github.com/spritsail/libressl
This is the kick up the arse I needed to go and clean all of this old stuff up- thanks

**Comment by milkpirate** [comment]
Well I really like the image, becuase you could copy some binaries with its libraries into it and they run. The only thing thats missing IMHO is curl with full TLS support. I copied the curl binary from this container: [https://hub.docker.com/r/yauritux/busybox-curl](https://hub.docker.com/r/yauritux/busybox-curl) but curl complains about certificates. Would be great if thats possible.

**Comment by frebib** [comment]
We build our Plex image on top of this image, and we build openssl/curl in that container. You can crib from the build steps there if you'd like. We decided not to include openssl/curl into this image because it's extra weight that in most case is not needed.
https://github.com/spritsail/plex-media-server/blob/master/Dockerfile#L97-L151

Ideally we'd not build anything into the images and have some form of central repository with these binaries packaged, but that seemed like a lot more effort. If you're using this for something that doesn't need glibc (e.g. you're building from source) then I'd suggest that Alpine may be a better fit.
To fix your certificate issue, copy `/etc/ssl/certs/ca-certificates.crt` from the build container to the final image.

**Comment by milkpirate** [comment]
- I will have a look
- Sure adding features adds weight
- I know about alpine and its musl but that wasnt suitable for my purpose (not even the alpine glibc version)
- Curl looks for certs in /usr/share/ssl/certs/ca-certs.crt (or similar) sym linking the package helped, but not for programms using libcurl. Thats why I am asking.

**Comment by frebib** [comment]
When building curl, it looks like you can override the path at which curl looks for the ca-certificate bundle in `./configure`, I'm not sure if that helps at all
```
 --with-ca-bundle=FILE   Path to a file containing CA certificates (example:
                         /etc/ca-bundle.crt)
 --without-ca-bundle     Don't use a default CA bundle
 --with-ca-path=DIRECTORY
                         Path to a directory containing CA certificates
                         stored individually, with their filenames in a hash
                         format. This option can be used with the OpenSSL,
                         GnuTLS and mbedTLS backends. Refer to OpenSSL
                         c_rehash for details. (example: /etc/certificates)
 --without-ca-path       Don't use a default CA path
 --with-ca-fallback      Use the built in CA store of the SSL library
 --without-ca-fallback   Don't use the built in CA store of the SSL library
```
In the Plex container, we replace the bundled libcurl binary with the one that we build instead. Curiously though there seems to be no ca-cert bundle in that container :thinking: 
```
root@b054d9b406bf /u/l/plexmediaserver> ls -al /etc/ssl/certs
ls: /etc/ssl/certs: No such file or directory
```

Edit: huh, thanks. I never noticed that curl was unhappy in that container, so thanks for making me look :) I'll go fix that
```
root@b054d9b406bf /u/l/plexmediaserver> curl https://google.com
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none

root@b054d9b406bf /u/l/plexmediaserver> mkdir -p /etc/ssl/certs/
root@b054d9b406bf /u/l/plexmediaserver> ln -sfv /usr/lib/plexmediaserver/Resources/cacert.pem /etc/ssl/certs/
ca-certificates.crt
'/etc/ssl/certs/ca-certificates.crt' -> '/usr/lib/plexmediaserver/Resources/cacert.pem'

root@b054d9b406bf /u/l/plexmediaserver> curl https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```
